name: Build JAR File

on:
  pull_request:  # Trigger workflow only on pull requests
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Adjust Java version as needed

      # Check if lib folder exists
      - name: Check for dependencies folder
        id: lib-check
        run: |
          if [ -d "lib" ]; then
            echo "dependencies=true" >> $GITHUB_ENV
          else
            echo "dependencies=false" >> $GITHUB_ENV
          fi

      # Build JAR without dependencies
      - name: Build JAR (no dependencies)
        if: env.dependencies == 'false'
        run: |
          javac -d out $(find src -name "*.java")
          jar cfm myproject.jar manifest.txt -C out .

      # Build JAR with dependencies and resources
      - name: Build JAR (with dependencies and resources)
        if: env.dependencies == 'true'
        run: |
          javac -d out -cp "lib/*" $(find src -name "*.java")
          jar cfm myproject.jar manifest.txt -C out . -C lib .

      # Upload the JAR as an artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: myproject
          path: myproject.jar
