name: Build JAR File

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-jar:
    runs-on: ubuntu-latest # Use a Linux machine to build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        path: repo # Ensure it matches your structure

    - name: Set Up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17' # Adjust this based on your project requirements

    - name: Compile Java Files
      working-directory: repo/10-16-2024\ PhotoViewierAssignment
      run: |
        mkdir -p out # Create the output directory
        javac -d out src/*.java

    - name: Create JAR File
      working-directory: repo/10-16-2024\ PhotoViewierAssignment
      run: |
        jar cvfm myproject.jar manifest.txt -C out .
        mv myproject.jar ../../JAR\ File/ # Move the JAR file to the "JAR File" folder
