name: Build JAR File

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Adjust Java version as needed

      # Check if lib/images folder exists
      - name: Check for dependencies folder
        id: lib-check
        run: |
          if [ -d "10-16-2024 PhotoViewierAssignment/lib/images" ]; then
            echo "dependencies=true" >> $GITHUB_ENV
          else
            echo "dependencies=false" >> $GITHUB_ENV
          fi

      # Build JAR without dependencies
      - name: Build JAR (no dependencies)
        if: env.dependencies == 'false'
        run: |
          mkdir -p out
          javac -d out $(find "10-16-2024 PhotoViewierAssignment/src" -name "*.java")
          jar cfm myproject.jar "10-16-2024 PhotoViewierAssignment/manifest.txt" -C out .

      # Build JAR with dependencies and resources
      - name: Build JAR (with dependencies and resources)
        if: env.dependencies == 'true'
        run: |
          mkdir -p out
          javac -d out -cp "10-16-2024 PhotoViewierAssignment/lib/images/*" $(find "10-16-2024 PhotoViewierAssignment/src" -name "*.java")
          jar cfm myproject.jar "10-16-2024 PhotoViewierAssignment/manifest.txt" -C out . -C "10-16-2024 PhotoViewierAssignment/lib/images" .

      # Move the JAR to the JAR Files directory
      - name: Add JAR to JAR Files directory
        run: |
          mkdir -p "JAR Files"
          mv myproject.jar "JAR Files/"

      # Commit and push the JAR file to the repository
      - name: Commit and Push JAR
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add "JAR Files/myproject.jar"
          git commit -m "Add built JAR file [$(date)]"
          git push
